#pragma once
#include <windows.h>

enum Direction
{
	Up,
	Right,
	Down,
	Left
};

enum Colors // для установки цвета танка
{
	DarkRed = FOREGROUND_RED,
	DarkBlue = FOREGROUND_BLUE,
	DarkGreen = FOREGROUND_GREEN,
	DarkMagenta = FOREGROUND_RED | FOREGROUND_BLUE,
	DarkCyan = FOREGROUND_BLUE | FOREGROUND_GREEN,
	DarkYellow = FOREGROUND_RED | FOREGROUND_GREEN,
	DarkGrey = FOREGROUND_INTENSITY,
	Red = FOREGROUND_RED | FOREGROUND_INTENSITY,
	Blue = FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	Green = FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	Magenta = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	Cyan = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	Yellow = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	Black = 0,
	Grey = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN,
	White = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
};